---
checkpoint:
  root_dir: 'ckpt/exp04'
  prefix: 'exp04'

weight: 'ckpt/exp04/exp04_VGG_15.pth'

device: 'cuda:0'  # 'cuda:0', 'cuda:1', ... or 'cpu'

model:
  backbone:
    name: 'VGG'
    pretrained: True

train:
  num_epochs: 15
  viz: False

  optimizer:
    name: 'Adam'
    lr: 0.001

  loss:
    name: 'hinge'

  dataset:
    name: 'FlickrPro'
    root_dir: '../datasets/FlickrPro/src/'
    gulpio_dir: '../datasets/FlickrPro/train/'

  dataloader:
    batch_size: 50
    shuffle: False

validation:
  viz: False

  dataset:
    name: 'FlickrPro'
    root_dir: '../datasets/FlickrPro/src/'
    gulpio_dir: '../datasets/FlickrPro/val/'

  dataloader:
    batch_size: 50
    shuffle: False


evaluate:
  FCDB:
    root_dir: '../datasets/FCDB'
    download: False

  ICDB:
    root_dir: '../datasets/ICDB'
    download: True
...
