---
checkpoint:
  root_dir: 'ckpt/exp02'
  prefix: 'exp02'

weight: 'ckpt/exp02/exp02_AlexNet_6.pth'

device: 'cuda:0'  # 'cuda:0', 'cuda:1', ... or 'cpu'

model:
  backbone:
    name: 'AlexNet'
    pretrained: True

train:
  num_epochs: 15
  viz: True

  optimizer:
    name: 'Adam'
    lr: 0.001

  loss:
    name: 'hinge'

  dataset:
    name: 'FlickrPro'
    root_dir: '../datasets/FlickrPro/src/'
    gulpio_dir: '../datasets/FlickrPro/train/'

  dataloader:
    batch_size: 128
    shuffle: False

validation:
  viz: True

  dataset:
    name: 'FlickrPro'
    root_dir: '../datasets/FlickrPro/src/'
    gulpio_dir: '../datasets/FlickrPro/val/'

  dataloader:
    batch_size: 128
    shuffle: False


evaluate:
  FCDB:
    root_dir: '../FCDB'
    download: False

  ICDB:
    root_dir: '../ICDB'
    download: False
...