---
checkpoint:
  root_dir: 'ckpt/exp01'
  prefix: 'exp01'

weight: 'ckpt/exp01/exp01_AlexNet_17.pth'

device: 'cuda:0'  # 'cuda:0', 'cuda:1', ... or 'cpu'

model:
  backbone:
    name: 'AlexNet'
    pretrained: True

train:
  num_epochs: 10

  optimizer:
    name: 'Adam'
    lr: 0.001

  loss:
    name: 'hinge'

  dataset:
    name: 'FlickrPro'
    root_dir: 'raw_images/flickr_pro'
    gulpio_dir: 'gulpio'
    train_size: 400

  dataloader:
    batch_size: 100
    shuffle: True

validation:
  dataloader:
    batch_size: 100
    shuffle: False

evaluate:
  FCDB:
    root_dir: 'FCDB'
    download: False

  ICDB:
    root_dir: 'ICDB'
    download: False
...